#!/usr/bin/env python3
"""
Export paper-ready tables and graph-ready JSON/CSV from benchmark raw metrics.

This script consumes benchmark_results/raw_metrics/*.json files generated by
run_benchmark.py and writes:
1) Proximity RL communication table (mean +- std)
2) Fixed vs density vs proximity traffic comparison (mean +- std)
3) Security impact table (no-security vs with-security + percentage change)
4) Graph-ready aggregated time-series JSON and long-format CSV

Usage:
  python export_paper_metrics.py
  python export_paper_metrics.py --results-dir benchmark_results --seed-start 42 --seed-count 30
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import statistics
from datetime import datetime, timezone
from typing import Any


def load_raw_runs(results_dir: str) -> list[dict[str, Any]]:
    raw_dir = os.path.join(results_dir, "raw_metrics")
    files = sorted(glob.glob(os.path.join(raw_dir, "*.json")))
    runs: list[dict[str, Any]] = []
    for path in files:
        try:
            with open(path, "r", encoding="utf-8") as f:
                runs.append(json.load(f))
        except Exception:
            continue
    return runs


def safe_mean_std(values: list[float]) -> tuple[float, float]:
    if not values:
        return 0.0, 0.0
    return float(statistics.fmean(values)), float(statistics.pstdev(values))


def fmt_pm(mean: float, std: float, unit: str = "") -> str:
    suffix = unit if unit else ""
    return f"{mean:.2f}+-{std:.2f}{suffix}"


def select_runs(
    runs: list[dict[str, Any]],
    mode: str | None = None,
    security: bool | None = None,
    seed_set: set[int] | None = None,
) -> list[dict[str, Any]]:
    selected = []
    for run in runs:
        run_mode = run.get("mode")
        run_sec = bool(run.get("security", False))
        run_seed = run.get("seed")

        if mode is not None and run_mode != mode:
            continue
        if security is not None and run_sec != security:
            continue
        if seed_set is not None:
            try:
                if int(run_seed) not in seed_set:
                    continue
            except Exception:
                continue
        selected.append(run)
    return selected


def metric_values(records: list[dict[str, Any]], key: str) -> list[float]:
    out: list[float] = []
    for r in records:
        v = r.get(key)
        if v is None:
            continue
        try:
            out.append(float(v))
        except Exception:
            continue
    return out


def compute_proximity_comm_table(
    runs: list[dict[str, Any]],
    seed_set: set[int],
    security: bool,
) -> dict[str, Any]:
    recs = select_runs(runs, mode="proximity", security=security, seed_set=seed_set)

    specs = [
        ("overall_pdr", "Overall PDR", "%"),
        ("v2v_pdr", "V2V PDR", "%"),
        ("v2i_pdr", "V2I PDR", "%"),
        ("avg_latency_ms", "Average Latency", "ms"),
        ("emergency_comm_avg_delay_ms", "Average Delay in Emergency Vehicle Communication", "ms"),
        ("emergency_comm_success_rate", "Success Rate of Emergency Vehicle Communication", "%"),
    ]

    rows = []
    for key, label, unit in specs:
        vals = metric_values(recs, key)
        mean, std = safe_mean_std(vals)
        rows.append(
            {
                "metric_key": key,
                "metric": label,
                "unit": unit,
                "n": len(vals),
                "mean": mean,
                "std": std,
                "value_pm": fmt_pm(mean, std, unit),
            }
        )

    return {
        "table": "proximity_rl_logic",
        "security": "with_security" if security else "no_security",
        "seed_count": len(seed_set),
        "rows": rows,
    }


def compute_mode_comparison_table(
    runs: list[dict[str, Any]],
    seed_set: set[int],
    security: bool,
) -> dict[str, Any]:
    modes = [
        ("fixed", "Fixed-time Control"),
        ("density", "Density-based Control"),
        ("proximity", "Proposed RL Control"),
    ]

    metrics = [
        ("normal_avg_wait", "Average Wait Time of Normal Vehicles (s)", "s"),
        ("emergency_avg_wait", "Average Wait Time of Emergency Vehicles (s)", "s"),
        ("normal_avg_queue_length", "Average Queue Length (normal vehicles)", ""),
        ("emergency_avg_queue_length", "Average Queue Length (emergency vehicles)", ""),
        ("avg_trip_speed", "Average Trip Speed (m/s)", "m/s"),
    ]

    rows: list[dict[str, Any]] = []
    for key, label, unit in metrics:
        row: dict[str, Any] = {
            "metric_key": key,
            "metric": label,
            "unit": unit,
        }
        for mode_key, mode_label in modes:
            recs = select_runs(runs, mode=mode_key, security=security, seed_set=seed_set)
            vals = metric_values(recs, key)
            mean, std = safe_mean_std(vals)
            row[mode_label] = {
                "n": len(vals),
                "mean": mean,
                "std": std,
                "value_pm": fmt_pm(mean, std),
            }
        rows.append(row)

    return {
        "table": "traffic_mode_comparison",
        "security": "with_security" if security else "no_security",
        "seed_count": len(seed_set),
        "rows": rows,
    }


def percent_change(new: float, old: float) -> float:
    if old == 0:
        return 0.0
    return ((new - old) / abs(old)) * 100.0


def compute_security_impact_table(runs: list[dict[str, Any]], seed_set: set[int]) -> dict[str, Any]:
    nosec_recs = select_runs(runs, mode="proximity", security=False, seed_set=seed_set)
    sec_recs = select_runs(runs, mode="proximity", security=True, seed_set=seed_set)

    specs = [
        ("throughput_veh_per_min", "Throughput (vehicles/min)", ""),
        ("avg_latency_ms", "Avg Communication Latency (ms)", "ms"),
        ("emergency_comm_avg_delay_ms", "Emergency vehicle communication latency (ms)", "ms"),
        ("v2v_pdr", "V2V PDR (%)", "%"),
        ("v2i_pdr", "V2I PDR (%)", "%"),
        ("emergency_comm_success_rate", "Emergency vehicle communication Success (%)", "%"),
    ]

    rows = []
    for key, label, unit in specs:
        vals_nosec = metric_values(nosec_recs, key)
        vals_sec = metric_values(sec_recs, key)

        m_nosec, s_nosec = safe_mean_std(vals_nosec)
        m_sec, s_sec = safe_mean_std(vals_sec)
        delta_pct = percent_change(m_sec, m_nosec)

        rows.append(
            {
                "metric_key": key,
                "metric": label,
                "unit": unit,
                "no_security": {
                    "n": len(vals_nosec),
                    "mean": m_nosec,
                    "std": s_nosec,
                    "value_pm": fmt_pm(m_nosec, s_nosec),
                    "value_mean": round(m_nosec, 2),
                },
                "with_security": {
                    "n": len(vals_sec),
                    "mean": m_sec,
                    "std": s_sec,
                    "value_pm": fmt_pm(m_sec, s_sec),
                    "value_mean": round(m_sec, 2),
                },
                "change_percent": delta_pct,
            }
        )

    return {
        "table": "security_impact_proximity",
        "seed_count": len(seed_set),
        "rows": rows,
    }


def aggregate_series(records: list[dict[str, Any]], key: str) -> dict[str, Any]:
    series = [r.get(key, []) for r in records if isinstance(r.get(key), list) and r.get(key)]
    if not series:
        return {"n_series": 0, "mean": [], "std": []}

    max_len = max(len(s) for s in series)
    mean_series: list[float] = []
    std_series: list[float] = []

    for idx in range(max_len):
        vals = []
        for s in series:
            if idx < len(s):
                try:
                    vals.append(float(s[idx]))
                except Exception:
                    pass
        mean, std = safe_mean_std(vals)
        mean_series.append(mean)
        std_series.append(std)

    return {
        "n_series": len(series),
        "mean": mean_series,
        "std": std_series,
    }


def build_graph_data(runs: list[dict[str, Any]], seed_set: set[int]) -> dict[str, Any]:
    series_specs = [
        "per_step_delay_ms",
        "per_step_wait_time",
        "per_step_queue_length",
        "per_step_emergency_wait",
    ]

    payload: dict[str, Any] = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "seed_range": {
            "min": min(seed_set) if seed_set else None,
            "max": max(seed_set) if seed_set else None,
            "count": len(seed_set),
        },
        "timeseries": {
            "no_security": {},
            "with_security": {},
        },
    }

    for sec_value, sec_label in [(False, "no_security"), (True, "with_security")]:
        for mode in ["fixed", "density", "proximity"]:
            recs = select_runs(runs, mode=mode, security=sec_value, seed_set=seed_set)
            payload["timeseries"][sec_label][mode] = {
                "n_runs": len(recs),
            }
            for key in series_specs:
                payload["timeseries"][sec_label][mode][key] = aggregate_series(recs, key)

    return payload


def write_json(path: str, payload: Any) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def write_proximity_table_csv(path: str, table: dict[str, Any]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Metric", "Mean", "Std", "Value"])
        for row in table["rows"]:
            writer.writerow([row["metric"], f"{row['mean']:.4f}", f"{row['std']:.4f}", row["value_pm"]])


def write_mode_comparison_csv(path: str, table: dict[str, Any]) -> None:
    mode_columns = ["Fixed-time Control", "Density-based Control", "Proposed RL Control"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Metric"] + mode_columns)
        for row in table["rows"]:
            writer.writerow(
                [
                    row["metric"],
                    row[mode_columns[0]]["value_pm"],
                    row[mode_columns[1]]["value_pm"],
                    row[mode_columns[2]]["value_pm"],
                ]
            )


def write_security_impact_csv(path: str, table: dict[str, Any]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Metric", "No Security", "With Security", "Change (%)"])
        for row in table["rows"]:
            writer.writerow(
                [
                    row["metric"],
                    f"{row['no_security']['value_mean']:.2f}",
                    f"{row['with_security']['value_mean']:.2f}",
                    f"{row['change_percent']:+.2f}",
                ]
            )


def write_timeseries_long_csv(path: str, graph_data: dict[str, Any]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["security", "mode", "metric", "step", "mean", "std", "n_series"])

        for sec_label, sec_block in graph_data.get("timeseries", {}).items():
            for mode, mode_block in sec_block.items():
                for metric in [
                    "per_step_delay_ms",
                    "per_step_wait_time",
                    "per_step_queue_length",
                    "per_step_emergency_wait",
                ]:
                    metric_block = mode_block.get(metric, {})
                    n_series = metric_block.get("n_series", 0)
                    means = metric_block.get("mean", [])
                    stds = metric_block.get("std", [])
                    for idx, (mean, std) in enumerate(zip(means, stds), start=1):
                        writer.writerow([sec_label, mode, metric, idx, f"{mean:.6f}", f"{std:.6f}", n_series])


def write_summary(path: str, runs: list[dict[str, Any]], seed_set: set[int]) -> None:
    expected = {
        "total": 3 * 2 * len(seed_set),
        "modes": ["fixed", "density", "proximity"],
        "security": [False, True],
    }
    summary: dict[str, Any] = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "expected_runs": expected,
        "actual_total_runs_in_seed_range": 0,
        "counts": {},
        "missing": [],
    }

    count_map: dict[str, int] = {}
    for sec in [False, True]:
        for mode in ["fixed", "density", "proximity"]:
            recs = select_runs(runs, mode=mode, security=sec, seed_set=seed_set)
            key = f"{mode}|{'sec' if sec else 'nosec'}"
            count_map[key] = len(recs)
            summary["actual_total_runs_in_seed_range"] += len(recs)

            found_seeds = set()
            for r in recs:
                try:
                    found_seeds.add(int(r.get("seed")))
                except Exception:
                    pass

            for seed in sorted(seed_set):
                if seed not in found_seeds:
                    summary["missing"].append(
                        {
                            "mode": mode,
                            "security": sec,
                            "seed": seed,
                        }
                    )

    summary["counts"] = count_map
    write_json(path, summary)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export paper metrics and graph-ready JSON/CSV")
    parser.add_argument("--results-dir", type=str, default="benchmark_results", help="Directory containing raw_metrics/")
    parser.add_argument("--output-dir", type=str, default=os.path.join("benchmark_results", "paper_exports"), help="Directory to write exported files")
    parser.add_argument("--seed-start", type=int, default=42, help="First seed to include")
    parser.add_argument("--seed-count", type=int, default=30, help="Number of consecutive seeds to include")
    args = parser.parse_args()

    results_dir = os.path.abspath(args.results_dir)
    output_dir = os.path.abspath(args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    seed_set = set(range(args.seed_start, args.seed_start + args.seed_count))
    runs = load_raw_runs(results_dir)

    if not runs:
        raise RuntimeError(f"No raw metrics found in: {os.path.join(results_dir, 'raw_metrics')}")

    table_prox_nosec = compute_proximity_comm_table(runs, seed_set, security=False)
    table_prox_sec = compute_proximity_comm_table(runs, seed_set, security=True)
    table_modes_nosec = compute_mode_comparison_table(runs, seed_set, security=False)
    table_security_impact = compute_security_impact_table(runs, seed_set)
    graph_data = build_graph_data(runs, seed_set)

    # JSON outputs (graphing + exact numeric traceability)
    write_json(os.path.join(output_dir, "table_proximity_rl_no_security.json"), table_prox_nosec)
    write_json(os.path.join(output_dir, "table_proximity_rl_with_security.json"), table_prox_sec)
    write_json(os.path.join(output_dir, "table_control_comparison_no_security.json"), table_modes_nosec)
    write_json(os.path.join(output_dir, "table_security_impact_proximity.json"), table_security_impact)
    write_json(os.path.join(output_dir, "graph_timeseries_aggregated.json"), graph_data)

    # CSV outputs (quick paste into spreadsheets / paper drafting)
    write_proximity_table_csv(os.path.join(output_dir, "table_proximity_rl_no_security.csv"), table_prox_nosec)
    write_proximity_table_csv(os.path.join(output_dir, "table_proximity_rl_with_security.csv"), table_prox_sec)
    write_mode_comparison_csv(os.path.join(output_dir, "table_control_comparison_no_security.csv"), table_modes_nosec)
    write_security_impact_csv(os.path.join(output_dir, "table_security_impact_proximity.csv"), table_security_impact)
    write_timeseries_long_csv(os.path.join(output_dir, "graph_timeseries_aggregated.csv"), graph_data)

    write_summary(os.path.join(output_dir, "export_summary.json"), runs, seed_set)

    print("=" * 72)
    print("PAPER METRICS EXPORT COMPLETE")
    print("=" * 72)
    print(f"Results dir: {results_dir}")
    print(f"Output dir : {output_dir}")
    print(f"Seeds      : {min(seed_set)}-{max(seed_set)} ({len(seed_set)} total)")
    print("Files written:")
    for name in [
        "table_proximity_rl_no_security.json",
        "table_proximity_rl_with_security.json",
        "table_control_comparison_no_security.json",
        "table_security_impact_proximity.json",
        "graph_timeseries_aggregated.json",
        "table_proximity_rl_no_security.csv",
        "table_proximity_rl_with_security.csv",
        "table_control_comparison_no_security.csv",
        "table_security_impact_proximity.csv",
        "graph_timeseries_aggregated.csv",
        "export_summary.json",
    ]:
        print(f"  - {os.path.join(output_dir, name)}")


if __name__ == "__main__":
    main()
